baseURL = "https://igornelke.pl/"
languageCode = "pl"
defaultContentLanguage = "pl"
title = "Igor Nelke"
theme = "PaperMod"
copyright = "&copy; 2026"

[params]
    defaultTheme = "dark"
    dateFormat = "02.01.2006"
    customCSS = ["css/custom.css"]
    alert = { enabled = true, text = "Zapraszamy do zapoznania sie z naszym [systemem ITOS](https://l.igornelke.pl/iS8Fj)" }

[params.footer]
    text = "Komitet Wyborczy Kandydata na Prezydenta Samorządu Uczniowskiego Igora Nelke"

[params.profileMode]
    enabled = true
    title = "Igor Nelke"
    subtitle = "Kandydat na Prezydenta Samorządu Uczniowskiego"
    imageUrl = "/images/igor-start.png"
    imageTitle = "Igor Nelke"
    imageWidth = 200
    imageHeight = 200

    [[params.profileMode.buttons]]
        name = "Aktualności"
        url = "/posts"

[[params.socialIcons]]
    name = "email"
    url = "mailto:komitet@igornelke.pl"

[[params.socialIcons]]
    name = "instagram"
    url = "<link>"

[[params.socialIcons]]
    name = "facebook"
    url = "<link2>"


[menus]
    [[menus.main]]
        name = "Start"
        pageRef = "/"
        weight = 10
    [[menus.main]]
        name = "Dotychczasowa działalność"
        pageRef = "/dzialalnosc"
        weight = 20
    [[menus.main]]
        name = "Komitet"
        pageRef = "/komitet"
        weight = 30
    [[menus.main]]
        name = "Program"
        pageRef = "/program"
        weight = 40